#!/bin/sh
NAGIOS="nagios-3.5.1"
Nagios_Plugins="nagios-plugins-1.4.16"
libsetups=(
"yum install gcc glibc glibc-common -y"
"yum install gd gd-devel -y"
"yum install httpd php php-gd -y"
"yum install mysql* -y"
"yum -y install perl"
"yum -y install perl-devel"
)
NRPE="nrpe-2.12"
#setup lib
function libsetup(){
for((libsetup=0;libsetup<${#libsetups[*]};libsetup++))
     do
     while true
        do
          ${libsetups[libsetup]} &>/dev/null
          if [ $? -eq 0 ];then
             break
          fi
     done
done
echo "lib install finish!"
}
function nagiosuseradd(){
useradd nagios
groupadd nagcmd
usermod -a -G nagcmd nagios
usermod -a -G nagcmd apache
if [ "`id apache|grep nagcmd|wc -l`" -eq 1 -a "`id nagios|grep nagcmd|wc -l`" -eq 1 ];then
   echo "useradd nagios and groups nagcmd finish!"
fi
}    
#setup nagios 
function nagiossetup(){
cd /server/tools/
tar xzf $NAGIOS.tar.gz 
cd nagios
./configure --with-command-group=nagcmd &>/dev/null
if [ $? -ne 0 ] 
  then
      echo "$NAGIOS configure error"
      exit 1
fi  
MAKES=(
"make all"
"make install"
"make install-init"
"make install-commandmode"
"make install-config"
"make install-webconf"
"htpasswd -cb /usr/local/nagios/etc/htpasswd.users admin 123456"
)
for((i=0;i<${#MAKES[*]};i++))
   do
     ${MAKES[i]} &>/dev/null
     if [ $? -ne 0 ]
        then
     echo "${NAGIOS} ${MAKES[i]} error!"
     exit 2
     fi
done
echo "${NAGIOS} install finish!"
}
# setup nagios-plugins
function npluginssetup(){
cd /server/tools
tar zxf ${Nagios_Plugins}.tar.gz
cd ${Nagios_Plugins}
./configure --with-nagios-user=nagios --with-nagios-group=nagios --enable-perl-modules --with-mysql &>/dev/null
if [ $? -ne 0 ]
  then
      echo "${Nagios_Plugins} configure error!"
      exit 4
fi
make &>/dev/nul&&make install &>/dev/null
if [ $? -ne 0 ]
  then
     echo "${Nagios_Plugins} make install error!"
     exit 3
fi
echo "${Nagios_Plugins} install finish!"
}
#setup nrpe
function nrpesetup(){
cd /server/tools
tar zxf ${NRPE}.tar.gz
cd ${NRPE}
./configure  &>/dev/null
if [ $? -ne 0 ]
  then
      echo "${NRPE} configure error!"
      exit 4
fi
MAKES=(
"make all"
"make install-plugin"
"make install-daemon"
"make install-daemon-config"
)
for((i=0;i<${#MAKES[*]};i++))
   do
     ${MAKES[i]} &>/dev/null
     if [ $? -ne 0 ]
        then
     echo "${NRPE} ${MAKES[i]} error!"
     exit 5
     fi
done
echo "${NRPE} install finish!"
}
function main(){
libsetup
nagiosuseradd
nagiossetup
npluginssetup
nrpesetup
echo "nagios server install finish!"
}
main
